import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faBolt,
  faCodeBranch,
  faDiagramProject,
  faGaugeHigh,
  faWandMagicSparkles,
  faLayerGroup,
  faListCheck,
  faShieldHalved,
  faServer,
  faRoute,
  faBoxOpen,
  faArrowsRotate,
  faClockRotateLeft,
  faSignal,
  faSitemap,
  faCubes,
  faFlaskVial,
  faImage,
  faHourglassHalf,
  faCircleNodes,
  faKeyboard,
  faBrain,
  faLock,
  faPuzzlePiece,
  faTerminal,
  faTableColumns,
  faWrench,
  faFileCode,
  faBug,
  faRocket,
  faStar,
  faTriangleExclamation,
  faScrewdriverWrench,
  faLeaf,
  faFeather,
  faGears,
  faMicrochip,
  faDatabase,
  faNetworkWired,
  faEye,
  faBookOpen,
  faGraduationCap,
  faCircleCheck,
  faCircleQuestion,
  faCode,
  faPlay,
  faForward,
  faObjectGroup,
  faTags,
  faFingerprint,
  faRecycle,
} from '@fortawesome/free-solid-svg-icons';
import { faAngular, faJs } from '@fortawesome/free-brands-svg-icons';

/** String-keyed registry so content data can reference icons without importing them. */
export const ICONS: Record<string, IconDefinition> = {
  angular: faAngular,
  typescript: faJs,
  bolt: faBolt,
  branch: faCodeBranch,
  project: faDiagramProject,
  gauge: faGaugeHigh,
  magic: faWandMagicSparkles,
  layers: faLayerGroup,
  checklist: faListCheck,
  shield: faShieldHalved,
  server: faServer,
  route: faRoute,
  box: faBoxOpen,
  rotate: faArrowsRotate,
  history: faClockRotateLeft,
  signal: faSignal,
  sitemap: faSitemap,
  cubes: faCubes,
  flask: faFlaskVial,
  image: faImage,
  hourglass: faHourglassHalf,
  nodes: faCircleNodes,
  keyboard: faKeyboard,
  brain: faBrain,
  lock: faLock,
  puzzle: faPuzzlePiece,
  terminal: faTerminal,
  columns: faTableColumns,
  wrench: faWrench,
  fileCode: faFileCode,
  bug: faBug,
  rocket: faRocket,
  star: faStar,
  warn: faTriangleExclamation,
  tools: faScrewdriverWrench,
  leaf: faLeaf,
  feather: faFeather,
  gears: faGears,
  chip: faMicrochip,
  database: faDatabase,
  network: faNetworkWired,
  eye: faEye,
  book: faBookOpen,
  grad: faGraduationCap,
  check: faCircleCheck,
  question: faCircleQuestion,
  code: faCode,
  play: faPlay,
  forward: faForward,
  group: faObjectGroup,
  tags: faTags,
  fingerprint: faFingerprint,
  recycle: faRecycle,
};

export function icon(key: string | undefined): IconDefinition {
  return (key && ICONS[key]) || faStar;
}
